### ISSUE TITLE
[UPDATE] Incompatible with Fabric version 1.21.4

### ISSUE THREAD

**Issue by marvinwz** [maxomatic458/playit-minecraft-mod#14]
Hey, I have been wanting to setup a Minecraft fabric 1.21.4 server using this mod. However, the current version doesn't work with fabric version 1.21.4. It does work with fabric 1.21.1, but I can't seem to get it working with version 1.21.4.

I am using fabric version 0.16.9 and I have tried using the Fabric API version 0.111.0 and 1.112.2 but both don't seem to work. The mod version I am using is playit-gg 1.3.2 Fabric [1.20.X-1.21.X]. 
Here is the crash report:

```
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'boolean net.minecraft.class_3222.method_5687(int)'
	at knot//gg.playit.playitfabric.PlayitFabric.onPlayerJoinDedicated(PlayitFabric.java:120)
	at knot//gg.playit.playitfabric.PlayitFabric.lambda$onInitializeServer$0(PlayitFabric.java:51)
	at knot//net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48)
	at knot//net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:63)
	at knot//net.minecraft.class_3324.handler$zfg000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:2488)
	at knot//net.minecraft.class_3324.method_14570(class_3324.java:203)
	at knot//net.minecraft.class_8610.method_52408(class_8610.java:152)
	at knot//net.minecraft.class_8736.method_53043(class_8736.java:22)
	at knot//net.minecraft.class_8736.method_65081(class_8736.java:8)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_3738.run(class_3738.java:18)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:164)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:889)
	at knot//net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:180)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:138)
	at knot//net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:871)
	at knot//net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:865)
	at knot//net.minecraft.class_1255.method_18857(class_1255.java:147)
	at knot//net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:829)
	at knot//net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:836)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:719)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

```
	Fabric Mods: 
		fabric-api: Fabric API 0.111.0+1.21.4
			fabric-api-base: Fabric API Base 0.4.53+453d4f9104
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.84+7feeb73304
			fabric-biome-api-v1: Fabric Biome API (v1) 15.0.4+466a140b04
			fabric-block-api-v1: Fabric Block API (v1) 1.0.31+7feeb73304
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.19+7feeb73304
			fabric-command-api-v1: Fabric Command API (v1) 1.2.61+f71b366f04
			fabric-command-api-v2: Fabric Command API (v2) 2.2.40+e496eb1504
			fabric-commands-v0: Fabric Commands (v0) 0.2.78+df3654b304
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.12+7feeb73304
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.6+7f945d5b04
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.6+466a140b04
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.6+7feeb73304
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.3+9aea556b04
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 22.1.2+466a140b04
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.10+7feeb73304
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.11+60fccc7604
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 4.0.1+a4eebcf004
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.62+7feeb73304
			fabric-item-api-v1: Fabric Item API (v1) 11.1.12+203e6b2304
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.21+7feeb73304
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.3+bf2a60eb04
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.31+3f89f5a504
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.19+203e6b2304
			fabric-message-api-v1: Fabric Message API (v1) 6.0.24+7feeb73304
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.8+cc0fa2fe04
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 18.0.5+e604fe7f04
			fabric-particles-v1: Fabric Particles (v1) 4.0.13+7feeb73304
			fabric-recipe-api-v1: Fabric Recipe API (v1) 8.0.3+fa62a02304
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 6.0.1+cc0fa2fe04
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.57+73761d2e04
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.18+7feeb73304
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.13+203e6b2304
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.10+203e6b2304
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.106+7feeb73304
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.6+1885ad7404
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.3.2+56e78b9b04
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.4
		playit_fabric: Playit Fabric 1.3.2
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.14.2
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.14.2
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.14.2
```

Would it be possible to add support for fabric 1.21.4 or is this an error on my side?

**Comment by yumm-dev** [comment]
The mod so far only supports 1.19.x, 1.20.x and 1.21(.1). To run a server on 1.21.4, you will have to get it running with regular Playit.gg until the mod updates.
